name: kavach_2
description: Kavach - Spam Alert App


publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  image: ^4.0.17
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  pinput: ^3.0.0
  get: ^4.6.5
  usage_stats: ^1.2.0
  installed_apps: ^1.3.1
  flutter_background_service: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.4.3
  google_maps_flutter: ^2.4.0
  cloud_firestore: ^4.8.4
  http: ^1.1.0
  flutter_sms_inbox: ^1.0.3
  google_nav_bar: ^5.0.6
  call_log: ^4.0.0
  workmanager: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/
    - assets/images/on_boarding_images/on-boarding-image.png
    - assets/images/splashscreen.png

  fonts:
    - family: abot
      fonts:
        - asset: assets/fonts/abot.ttf




  uses-material-design: true
































